# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
inheritance: true
reviews:
  request_changes_workflow: true
  review_details: true
  fail_commit_status: true
  poem: false
  pre_merge_checks:
    custom_checks:
      - mode: error
        name: min-level
        instructions: >-
          Fail the status check if you find any SECURITY RELATED major or critical issues. Do not
          fail the status check if there are trivial, nitpick, or minor issues, or not related to
          security.
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
    custom:
      - name: Update AGENTS.md
        instructions: Update AGENTS.md based on comments on this PR
chat:
  art: false
